### ISSUE TITLE
Move the AppStart class from the "com" package to the "com.alilitech" one

### ISSUE THREAD

**Issue by dbolkensteyn** [zhouxx/boot-plus#2]
I guess it was a mistake to place the `AppStart` class directly under the `com` package.
https://github.com/zhouxx/boot-plus/blob/master/boot-plus-core/src/main/java/com/AppStart.java#L16

**Comment by zhouxx** [comment]
Yes.Your are right! But my framework is to adapt to as many projects as possible. The packages of many projects start with `com`, maybe this will be able to adapt to more projects.
I means  that many projects do not need to write their own startup Class, just use the built-in framework.

**Comment by Diluka** [comment]
using `com.alilitech` is better than `com`
